copy g:\desenv\sindificios2009\sistemaxp.exe   J:\apoio\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\apoio /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\homero\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\aposentados\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\caixa /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\cleusa /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\denise /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\dias /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\edson /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\elcio /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\estoque /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\jailza\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\jeanne\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\jeanne /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\jose /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\tatiane /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\Tatiane\Sistema Novo /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\laura\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\liliana /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\lorival\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\luciano /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\paula\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\paulo\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\rodrigues\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\rh\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\santana\ /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\santo\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\seba /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\silvia /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\tonhao /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\tatuape\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\valter\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\homologacao /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\tonhão /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\valdecir /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\administrador /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\boarin\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\alexandre /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\joao\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\vanessa\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\daniela\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\miriam\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\lorival\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\isaias /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\luiz\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\samuel /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\user\josenildo /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\valdir /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\valter\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\vanessa\sindificios.exe /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\alexandre /y
copy g:\desenv\sindificios2009\sistemaxp.exe   J:\luiz\sindificios.exe /y