* // Criar DBF do TXT //
* CREATE arq.dbf
* APPEND FROM CBR64311.TXT SDF
*
CLEAR 
SET DEFAULT TO C:\BancoBrasil\BBTransf\Retorno\
CLOSE TABLES ALL

USE banco IN 1 EXCLUSIVE 
USE arq   IN 2 EXCLUSIVE  
SET Date BRITISH 

SELECT 1
ZAP
SELECT 2
ZAP

SELECT 1

APPEND FROM CBR64300.RET SDF
APPEND FROM CBR64301.RET SDF
APPEND FROM CBR64302.RET SDF
APPEND FROM CBR64303.RET SDF
*APPEND FROM CBR64304.RET SDF
*APPEND FROM CBR64305.RET SDF
*APPEND FROM CBR64306.RET SDF
*APPEND FROM CBR64307.RET SDF
*APPEND FROM CBR64308.RET SDF
*APPEND FROM CBR64309.RET SDF
*APPEND FROM CBR64310.RET SDF
*APPEND FROM CBR64311.RET SDF

ivVencto = CTOD("05/09/2007")
ivdescri = "CONFEDERATIVA"

SELECT 1
GO top

DO WHILE .not. EOF()
   STORE SUBSTR(LINHA1,69,5)   TO ivCOD         && COD
   STORE SUBSTR(LINHA1,147,19) TO ivVALOR       && VALOR
   STORE SUBSTR(ivVALOR,18,2)  TO ivV1
   STORE SUBSTR(ivVALOR,1,17)  TO ivV2
   STORE ivV2+"."+ivV1         TO ivVALOR     
   STORE SUBSTR(LINHA1,176,6)  TO ivDATA_PAGTO  && DATA ENTRA" 
   STORE SUBSTR(LINHA1,166,4)  TO ivAGENCIA     && AGENCIA
    
   STORE subSTR(ivDATA_PAGTO,1,2)       TO dt1
   STORE subSTR(ivDATA_PAGTO,3,2)       TO dt2
   STORE subSTR(ivDATA_PAGTO,5,2)       TO dt3
   STORE dt1+"/"+dt2+"/"+dt3            TO ivDATA_PAGTO
   
   @ 10,02 say ivCOD          && COD
   @ 11,02 say ivVALOR        && VALOR
   @ 12,02 say ivDATA_PAGTO   && DATA ENTRA" 
   @ 13,02 say ivAGENCIA      && AGENCIA
   
   SELECT 2
   IF INT(VAL(ivcod)) <> 0
	   APPEND BLANK 
	   REPLACE confcod        WITH INT(VAL(ivcod)) 
	   REPLACE data           WITH DATE()
	   REPLACE total          WITH VAL(ivvalor)
	   REPLACE pagto          WITH CTOD(ivdata_pagto)
	   REPLACE vencto         WITH ivVencto
	   REPLACE agencia        WITH ivagencia
	   REPLACE dat_bai        WITH DATE()
	   REPLACE descricao      WITH ivdescri
	   REPLACE venc_data      WITH ivVencto
	   
   ENDIF 	   
   SELECT 1
   SKIP
   LOOP
ENDDO

*CONFCOD
*DATA
*TOTAL
*PAGTO
*VENCTO
*AGENCIA
*DAT_BAI
*DESCRICAO
*VENC_DATA
